version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    environment:
      - FLASK_APP=/app
    command: flask run -h 0.0.0.0
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile-frontend
    volumes:
      - ./app/static:/app/static
    command: npm run watch
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: user
      MONGODB_DATABASE: dev
      MONGODB_PASS: user
    ports:
      - "27015:27017"
    logging:
      driver: none